### ISSUE TITLE
[EXE] not being removed

### ISSUE THREAD

**Issue by SUPERCILEX** [assert-rs/trycmd#140]
On windows, my tests are failing because [EXE] shows up: https://github.com/SUPERCILEX/ftzz/actions/runs/3161445260/jobs/5147037527. I thought it was supposed to be removed? In general, I don't understand variables. The docs are very unclear. Are they replacing input or output? Is the value a search string? Or is the var replaced with the value? Tried both and neither did anything. Examples are needed of what happens to the output or input when a variable is added.

**Comment by epage** [comment]
Variables are applied to the actual output so we the stored snapshots are consistent.

Still catching up on your other things so I can see what the full conversation is about improving this

**Comment by SUPERCILEX** [comment]
Hmmm, still don't get it unfortunately. Let say I have `t.insert_var("[FOO]", "Hello").unwrap();` And then this test:
```
$ echo-hello "[FOO]"
Hello [FOO]!
```

Why isn't `Hello` replaced with `[FOO]` (I think this is what's supposed to happen) or `[FOO]` replaced with `Hello` (or this)?

**Comment by epage** [comment]
A more complete reproduction case is needed to give you an answer.

**Comment by SUPERCILEX** [comment]
Can you describe what it's supposed to do? I still don't know since I've never seen it work.

**Comment by epage** [comment]
See the use of `[EXE]` in [this subsection](https://github.com/clap-rs/clap/blob/master/examples/tutorial_derive/04_02_validate.md) of clap's tutorial

On windows, we run the specified command.  We then normalize the output which includes finding `.exe` and replacing it with `[EXE]`.  We then compare this with the file on disk and error if they are different.  If the user instead specifies `overwrite`, we will write out the normalized output to disk.

On Linux, we see that `{EXE]` maps to nothing.  This works because when we normalize, we normalize to the file on disk as a template.  We see that `[EXE]` is on disk and so we keep it in the output.

**Comment by SUPERCILEX** [comment]
Ohhh, I get, thanks! So the example would be
```
$ echo-hello Blah
[FOO] Blah!
```
and `t.insert_var("[FOO]", "Hello").unwrap();` allows the `Hello` to optionally be replaced with `[FOO]` in the on-disk output.

**Comment by epage** [comment]
Yes!

I mainly use this for things that are dependent on the test environment (paths, file extensions, etc) but cargo-test-support, which this was partially based on, uses [variables for a lot more](https://github.com/rust-lang/cargo/blob/master/crates/cargo-test-support/src/compare.rs#L158).  Most of that is to make it easier to update as the tests using that are not using snapshots yet.

**Comment by epage** [comment]
clap-rs/clap#4348 serves as an example for `[EXE]`.  Someone added new examples that [failed on Windows](https://github.com/clap-rs/clap/actions/runs/3184689342/jobs/5193389864#step:6:1488) because the literal usage is `Usage: 04_01_enum_derive.exe <MODE>` on Windows so they [added EXE to the markdown](https://github.com/clap-rs/clap/compare/e52bd648410cc0a2a86db717ebef0a16977968c1..e644a5ef66896cf039b8de6169bd8c9d36f9c105) and it should now pass.

**Comment by SUPERCILEX** [comment]
Yup yup, I'm waiting on https://github.com/SUPERCILEX/ftzz/commit/122bf548eba2ca0a2aa7a6ede66c788860241573 to go green. Will reopen this issue if not.
